# Generated by Django 4.1.7 on 2023-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mkAuto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("couleur", models.CharField(max_length=200)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "carburant_consommation",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("tech_surete", models.CharField(max_length=200)),
                ("confort_conduit", models.CharField(max_length=200)),
                ("espace_interieur", models.CharField(max_length=200)),
                ("connectivite", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="car_images/")),
            ],
        ),
    ]
